project:
  type: website

website:
  title: "OPPE Coding Patterns"
  navbar:
    left:
      - href: index.qmd
        text: Home
      # - about.qmd
resources: 
  - "visualizations/**"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



