---
title: "OPPE Code Patterns"
---

This site is contains visualizations about different coding patterns observed from different OPPEs.

These are 10 programming problems from 24 September OPPE 1. In these visualizations each data point corresponds to individual code submission.

We created a 2D representation of these code submissions using an BERT-based model called Codesage. Which we clustered to find meaningful and interpretable clusters.

These names to the cluster were generated by an LLM summarizing the submissions. 

- You can hover over to see individual code submissions. 
- Zoom in by selecting a region.
- Click on the lables in the legend on the side to toggle the data points belonging to that clusters.

Note that these only contain a subset of all the submissions which are grouped as clusters.

You may find different patterns and different ways of approaching a problem, some might be correct some might be wrong. Try to compare different approaches to find what is better according to you.

M10 and M20 refers to the `min_cluster_size` hyperparameter used with the clustering algorithm.

**Note: These cluster/Pattern labels are generated using Large Language Models, which can be incorrect sometimes.**

|Problem Name| M20 Clusters | M10 Clusters (has fine grained patterns)|
|-|-|-|
|Increment Value Of Key In Dict With Max Limit | [M20](visualizations/24_sep_oppe1/m20/01_increment_value_of_key_in_dict_with_max_limit.html) | [M10](visualizations/24_sep_oppe1/m10/01_increment_value_of_key_in_dict_with_max_limit.html)|
|Check Positive Odd Or Negative Even | [M20](visualizations/24_sep_oppe1/m20/02_check_positive_odd_or_negative_even.html) | [M10](visualizations/24_sep_oppe1/m10/02_check_positive_odd_or_negative_even.html)|
|Last Word In A Given Sentence That Starts With Uppercase Letter | [M20](visualizations/24_sep_oppe1/m20/03_last_word_in_a_given_sentence_that_starts_with_uppercase_letter.html) | [M10](visualizations/24_sep_oppe1/m10/03_last_word_in_a_given_sentence_that_starts_with_uppercase_letter.html)|
|Count Positive Integers Ignoring None | [M20](visualizations/24_sep_oppe1/m20/04_count_positive_integers_ignoring_none.html) | [M10](visualizations/24_sep_oppe1/m10/04_count_positive_integers_ignoring_none.html)|
|Upper Case Only Vowels Cluster | [M20](visualizations/24_sep_oppe1/m20/05_upper_case_only_vowels_cluster.html) | [M10](visualizations/24_sep_oppe1/m10/05_upper_case_only_vowels_cluster.html)|
|Find Sum And Absolute Difference Alternately | [M20](visualizations/24_sep_oppe1/m20/06_find_sum_and_absolute_difference_alternately.html) | [M10](visualizations/24_sep_oppe1/m10/06_find_sum_and_absolute_difference_alternately.html)|
|Student Marks Filter | [M20](visualizations/24_sep_oppe1/m20/07_student_marks_filter.html) | [M10](visualizations/24_sep_oppe1/m10/07_student_marks_filter.html)|
|Matrix Walk Cluster | [M20](visualizations/24_sep_oppe1/m20/08_matrix_walk_cluster.html) | [M10](visualizations/24_sep_oppe1/m10/08_matrix_walk_cluster.html)|
|Print Pattern - V | [M20](visualizations/24_sep_oppe1/m20/09_print_pattern_-_v.html) | [M10](visualizations/24_sep_oppe1/m10/09_print_pattern_-_v.html)|
|Pattern Print - N | [M20](visualizations/24_sep_oppe1/m20/10_pattern_print_-_n.html) | [M10](visualizations/24_sep_oppe1/m10/10_pattern_print_-_n.html)|